# views/report_detail.py
import streamlit as st
import base64
from datetime import datetime
from utils.styles import get_theme
from utils.api import update_incident_media, get_incident_detail
from views.user_dashboard import user_sidebar


def _fmt_dt(val) -> str:
    """FIX 1: Format ISO datetime string to readable form e.g. 14 May 2026, 08:59 PM"""
    if not val:
        return "—"
    for fmt in ("%Y-%m-%dT%H:%M:%S", "%Y-%m-%d %H:%M:%S", "%Y-%m-%dT%H:%M:%S.%f"):
        try:
            return datetime.strptime(str(val), fmt).strftime("%d %b %Y, %I:%M %p")
        except ValueError:
            continue
    return str(val)  # fallback — return as-is if unparseable


def _show_image(data_str: str, caption: str):
    """Display image from base64 string or URL."""
    if not data_str:
        st.caption(f"No {caption} uploaded.")
        return
    try:
        img_bytes = base64.b64decode(data_str)
        st.image(img_bytes, caption=caption, use_container_width=True)
    except Exception:
        try:
            st.image(data_str, caption=caption, use_container_width=True)
        except Exception:
            st.caption(f"Cannot display {caption}.")


def _build_receipt(detail: dict) -> str:
    inc  = detail.get("incident", {})
    loc  = detail.get("location", {})
    vic  = detail.get("victim", {})
    stat = detail.get("case_status", {})

    def v(val):
        return str(val) if val else "—"

    return f"""
UCARS — Crime Report Receipt
========================================
Incident ID : {v(inc.get("incident_id"))}
Title       : {v(inc.get("title"))}
Category    : {v(inc.get("category_name"))}
Date        : {_fmt_dt(inc.get("incident_datetime"))}
Reported At : {_fmt_dt(inc.get("reported_at"))}
Description : {v(inc.get("description"))}
----------------------------------------
Area        : {v(loc.get("area_name"))}
Street      : {v(loc.get("street_address"))}
City        : {v(loc.get("city"))}
Postal Code : {v(loc.get("postal_code"))}
----------------------------------------
Victim Name : {v(vic.get("name"))}
CNIC        : {v(vic.get("cnic"))}
Phone       : {v(vic.get("phone"))}
Email       : {v(vic.get("email"))}
Address     : {v(vic.get("address"))}
----------------------------------------
Case Status : {v(stat.get("status_name"))}
========================================
Auto-generated by UCARS
"""


def show():
    get_theme()
    user_sidebar()

    data = st.session_state.get("selected_report")
    if not data:
        st.warning("⚠️ No report selected.")
        if st.button("← Back to Dashboard"):
            st.session_state.current_page = "user_dashboard"
            st.rerun()
        return

    inc      = data.get("incident", {})
    loc      = data.get("location", {})   # FIX 2: cctv lives here
    vic      = data.get("victim", {})
    stat     = data.get("case_status", {})
    suspects = data.get("suspects", [])
    stations = data.get("police_stations", [])
    sus      = suspects[0] if suspects else {}

    def v(val, default="— (pending admin)"):
        return str(val) if val else default

    def vd(val):
        return str(val) if val else "—"

    if st.button("← Back to Dashboard", key="back_btn"):
        st.session_state.current_page = "user_dashboard"
        st.rerun()

    st.title(f"🚨 {inc.get('title') or 'Incident Detail'}")
    st.caption(f"Incident ID: #{inc.get('incident_id') or '—'}")
    st.divider()

    # ── 1. CASE STATUS ──
    status = stat.get("status_name") or "Waiting"
    status_map = {
        "Waiting":                       st.warning,
        "Accepted; Under Investigation": st.info,
        "Investigated":                  st.success,
        "Rejected":                      st.error,
    }
    status_map.get(status, st.warning)(f"📌 Case Status: **{status}**")
    st.divider()

    # ── 2. VICTIM INFO ──
    st.subheader("👤 Victim Information")
    col1, col2 = st.columns(2)
    with col1:
        st.write(f"**Name:** {vd(vic.get('name'))}")
        st.write(f"**CNIC:** {vd(vic.get('cnic'))}")
        st.write(f"**Phone:** {vd(vic.get('phone'))}")
    with col2:
        st.write(f"**Email:** {vd(vic.get('email'))}")
        st.write(f"**Address:** {vd(vic.get('address'))}")
        st.write(f"**Injury Type:** {vd(vic.get('injury_type'))}")
    st.divider()

    # ── 3. INCIDENT INFO ──
    st.subheader("🚨 Incident Information")
    col1, col2 = st.columns(2)
    with col1:
        st.write(f"**Incident ID:** {vd(inc.get('incident_id'))}")
        st.write(f"**Title:** {vd(inc.get('title'))}")
        st.write(f"**Category:** {vd(inc.get('category_name'))}")
        # FIX 1: formatted datetime
        st.write(f"**Incident Date:** {_fmt_dt(inc.get('incident_datetime'))}")
        st.write(f"**Reported At:** {_fmt_dt(inc.get('reported_at'))}")
    with col2:
        st.write(f"**Area:** {vd(loc.get('area_name'))}")
        st.write(f"**Street:** {vd(loc.get('street_address'))}")
        st.write(f"**Postal Code:** {vd(loc.get('postal_code'))}")
        st.write(f"**City:** {vd(loc.get('city'))}")

    st.write("**Description:**")
    st.info(inc.get("description") or "No description provided.")
    st.divider()

    # ── 4. INVESTIGATION DETAILS (admin filled) ──
    st.subheader("🔍 Investigation Details")
    st.caption("These fields are filled by admin after investigation.")
    col1, col2 = st.columns(2)
    with col1:
        st.write(f"**Crime Severity:** {v(inc.get('crime_severity'))}")
    with col2:
        st.write(f"**Case Status:** {v(stat.get('status_name'))}")
    st.divider()

    # ── 5. SUSPECT INFO (admin filled) ──
    st.subheader("🕵️ Suspect Information")
    st.caption("Filled by admin after investigation.")

    if suspects:
        for i, s in enumerate(suspects, 1):
            with st.container(border=True):
                col1, col2 = st.columns(2)
                with col1:
                    st.write(f"**Name:** {v(s.get('suspect_name'))}")
                    st.write(f"**CNIC:** {v(s.get('suspect_cnic'))}")
                    st.write(f"**Status:** {v(s.get('suspect_status'))}")
                    st.write(f"**Arrest Date:** {v(s.get('arrest_date'))}")
                with col2:
                    _show_image(s.get("suspect_picture"), f"Suspect #{i}")
    else:
        with st.container(border=True):
            col1, col2 = st.columns(2)
            with col1:
                st.write("**Name:** — (pending admin)")
                st.write("**CNIC:** — (pending admin)")
                st.write("**Status:** — (pending admin)")
                st.write("**Arrest Date:** — (pending admin)")
            with col2:
                st.caption("No suspect picture yet.")
    st.divider()

    # ── 6. POLICE STATION (admin filled) ──
    st.subheader("🏫 Police Station Information")
    st.caption("Assigned by admin after investigation.")

    if stations:
        for ps in stations:
            with st.container(border=True):
                col1, col2 = st.columns(2)
                with col1:
                    st.write(f"**Station Name:** {v(ps.get('station_name'))}")
                    st.write(f"**City:** {v(ps.get('station_city'))}")
                    st.write(f"**Address:** {v(ps.get('station_address'))}")
                with col2:
                    st.write(f"**Incharge Officer:** {v(ps.get('incharge_officer_name'))}")
                    st.write(f"**Charges Filed:** {v(ps.get('charges_filed'))}")
    else:
        with st.container(border=True):
            col1, col2 = st.columns(2)
            with col1:
                st.write("**Station Name:** — (pending admin)")
                st.write("**City:** — (pending admin)")
                st.write("**Address:** — (pending admin)")
            with col2:
                st.write("**Incharge Officer:** — (pending admin)")
                st.write("**Charges Filed:** — (pending admin)")
    st.divider()

    # ── 7. EVIDENCE MEDIA ──
    st.subheader("📷 Evidence Media")
    col1, col2 = st.columns(2)
    with col1:
        st.write("**CCTV Footage / Image:**")
        # FIX 2: cctv_footage_path lives in loc (location), not inc
        _show_image(loc.get("cctv_footage_path"), "CCTV")
    with col2:
        st.write("**Suspect Picture:**")
        _show_image(sus.get("suspect_picture"), "Suspect Photo")

    with st.expander("📤 Update Media", expanded=False):
        um_col1, um_col2 = st.columns(2)
        with um_col1:
            st.write("**CCTV / Image**")
            new_cctv   = st.file_uploader(
                "Upload CCTV/Image",
                type=["jpg","jpeg","png","webp","mp4","avi","mov"],
                key="update_cctv"
            )
            clear_cctv = st.checkbox("Clear CCTV footage", key="clear_cctv")
        with um_col2:
            st.write("**Suspect Picture**")
            new_picture   = st.file_uploader(
                "Upload picture",
                type=["jpg","jpeg","png","webp"],
                key="update_picture"
            )
            clear_picture = st.checkbox("Clear suspect picture", key="clear_picture")

        if st.button("💾 Save Media Update", use_container_width=True):
            media_payload = {}
            if new_cctv:
                media_payload["cctv_footage_path"] = base64.b64encode(
                    new_cctv.read()).decode()
            elif clear_cctv:
                media_payload["cctv_footage_path"] = ""
            if new_picture:
                media_payload["picture_path"] = base64.b64encode(
                    new_picture.read()).decode()
            elif clear_picture:
                media_payload["picture_path"] = ""

            if not media_payload:
                st.warning("⚠️ No changes made.")
            else:
                if "cctv_footage_path" not in media_payload:
                    media_payload["cctv_footage_path"] = loc.get("cctv_footage_path") or ""
                if "picture_path" not in media_payload:
                    media_payload["picture_path"] = sus.get("suspect_picture") or ""

                with st.spinner("Saving..."):
                    result = update_incident_media(
                        inc.get("incident_id"), media_payload
                    )
                if result:
                    st.success("✅ Media updated successfully!")
                    updated = get_incident_detail(inc.get("incident_id"))
                    if updated:
                        st.session_state.selected_report = updated
                    st.rerun()
                else:
                    st.error("❌ Update failed.")
    st.divider()

    # ── 8. RECEIPT ──
    st.subheader("🧾 Download Receipt")

    if st.button("📄 Generate Receipt", key=f"gen_receipt_{inc.get('incident_id')}"):
        st.session_state["receipt_ready"] = _build_receipt(data)
        st.rerun()

    if st.session_state.get("receipt_ready"):
        st.download_button(
            label="⬇ Download Receipt (.txt)",
            data=st.session_state["receipt_ready"],
            file_name=f"receipt_{inc.get('incident_id', 'report')}.txt",
            mime="text/plain",
            key="dl_receipt_detail",
            use_container_width=True,
        )
        if st.button("✖ Close Receipt", key="close_receipt"):
            st.session_state["receipt_ready"] = None
            st.rerun()