# views/user_dashboard.py
import streamlit as st
from utils.styles import get_theme
from utils.auth import require_login
from utils.api import get_my_incidents, get_incident_detail


def user_sidebar():
    with st.sidebar:
        st.title("⚡ UCARS")
        st.divider()
        st.write(f"👤 **{st.session_state.get('user_name', 'User')}**")
        st.caption(st.session_state.get('user_email', ''))
        st.divider()
        st.caption("NAVIGATION")

        if st.button("🏠  Dashboard", key="sb_dashboard", use_container_width=True):
            st.session_state.current_page = "user_dashboard"
            st.rerun()

        if st.button("📋  New Form", key="sb_newform", use_container_width=True):
            st.session_state.current_page = "new_form"
            st.rerun()

        if st.button("🔍  Search", key="sb_search", use_container_width=True):
            st.session_state.current_page = "search"
            st.rerun()

        st.divider()

        if st.button("🚪  Logout", key="sb_logout", use_container_width=True):
            from utils.api import logout
            from utils.auth import logout_user
            st.query_params.clear()
            logout()
            logout_user()
            st.session_state.current_page = "home"
            st.rerun()


def _build_receipt(detail: dict) -> str:
    """Build receipt text from nested API response."""
    # ── Unpack nested keys ──
    inc  = detail.get("incident", {})
    loc  = detail.get("location", {})
    vic  = detail.get("victim", {})
    stat = detail.get("case_status", {})

    def v(val):
        return str(val) if val else "—"

    return f"""
UCARS — Crime Report Receipt
========================================
Incident ID : {v(inc.get("incident_id"))}
Title       : {v(inc.get("title"))}
Category    : {v(inc.get("category_name"))}
Date        : {v(inc.get("incident_datetime"))}
Reported At : {v(inc.get("reported_at"))}
Description : {v(inc.get("description"))}
----------------------------------------
Area        : {v(loc.get("area_name"))}
Street      : {v(loc.get("street_address"))}
City        : {v(loc.get("city"))}
Postal Code : {v(loc.get("postal_code"))}
----------------------------------------
Victim Name : {v(vic.get("name"))}
CNIC        : {v(vic.get("cnic"))}
Phone       : {v(vic.get("phone"))}
Email       : {v(vic.get("email"))}
Address     : {v(vic.get("address"))}
----------------------------------------
Case Status : {v(stat.get("status_name"))}
========================================
Auto-generated by UCARS
"""


def show():
    get_theme()
    require_login()
    user_sidebar()

    st.title("📋 My Reports")
    st.caption("All your submitted crime reports are listed below.")
    st.divider()

    with st.spinner("Loading your reports..."):
        response = get_my_incidents()

    reports = response.get("incidents", []) if response else []

    if not reports:
        st.info("📭 No reports yet. Click **New Form** in the sidebar to file your first report.")
        return

    for r in reports:
        with st.container(border=True):
            col1, col2 = st.columns([3, 1])

            with col1:
                st.write(f"**#{r.get('incident_id')} — {r.get('title', 'Untitled')}**")
                st.caption(
                    f"📁 {r.get('category_name', '—')}  |  "
                    f"📅 {r.get('incident_datetime', '—')}  |  "
                    f"📍 {r.get('area_name', '—')}"
                )

            with col2:
                # ── View button ──
                if st.button("📖 View", key=f"view_{r['incident_id']}"):
                    with st.spinner("Loading..."):
                        detail = get_incident_detail(r['incident_id'])
                    if detail:
                        st.session_state.selected_report = detail
                        st.session_state.current_page = "report_detail"
                        st.rerun()

                # ── Receipt button ──
                if st.button("📄 Receipt", key=f"receipt_btn_{r['incident_id']}"):
                    with st.spinner("Generating receipt..."):
                        detail = get_incident_detail(r['incident_id'])
                    if detail:
                        # Store receipt in session to render download outside column
                        st.session_state[f"receipt_data_{r['incident_id']}"] = _build_receipt(detail)
                        st.rerun()

        # ── Download button outside column — avoids layout bug ──
        receipt_key = f"receipt_data_{r['incident_id']}"
        if st.session_state.get(receipt_key):
            st.download_button(
                label=f"⬇ Download Receipt — #{r['incident_id']}",
                data=st.session_state[receipt_key],
                file_name=f"receipt_{r['incident_id']}.txt",
                mime="text/plain",
                key=f"dl_{r['incident_id']}",
                use_container_width=True,
            )
            if st.button("✖ Close", key=f"close_{r['incident_id']}"):
                st.session_state[receipt_key] = None
                st.rerun()